const vCardsJS = require('vcards-js');
const QRCode = require('qrcode');
const fs = require('fs');
const path = require('path');

// 1. Create a new vCard
const vCard = vCardsJS();
vCard.firstName = 'Aris';
vCard.lastName = 'Setyawan';
vCard.organization = 'Ares Project';
vCard.photo.attachFromUrl('https://avatars.githubusercontent.com/u/12345678?v=4', 'JPEG');
vCard.workPhone = '+628123456789';
vCard.title = 'Project Manager';
vCard.url = 'https://github.com/ariss';
vCard.note = 'Generated by Project Barcode';

// 2. Generate the vCard string
const vCardString = vCard.getFormattedString();

// 3. Define output path
const outputDir = path.join(__dirname, 'output');
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir);
}

const outputPath = path.join(outputDir, 'contact_qr.svg');

// 4. Generate QR code as SVG (best for printing)
QRCode.toFile(outputPath, vCardString, {
    type: 'svg',
    color: {
        dark: '#000000',  // Blue
        light: '#0000' // Transparent background
    },
    errorCorrectionLevel: 'H'
}, function (err) {
    if (err) throw err;
    console.log('✅ QR Code generated successfully at:', outputPath);
});
